spring.datasource.url=jdbc:mysql://localhost:3306/clinicaodontoapi?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
#Senha para entrar com usuario MySQL!
#spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

