spring.application.name=clinicaodotologica

# - usuario banco de dados
spring.datasource.username = root

# - senha banco de dados
spring.datasource.password = 1234

# - url banco de dados
spring.datasource.url = jdbc:mysql://localhost:3306/clinicaodontoapi?useTimezone=true&serverTimezone=UTC

# - dialeto do banco de dados
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
